language: cpp
dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
            - llvm-toolchain-trusty-5.0
        packages:
            - gcc-5
            - g++-5
            - gcc-6
            - g++-6
            - gcc-7
            - g++-7
            - clang-4.0
            - clang-5.0

env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    
before_install:
    - eval "${MATRIX_EVAL}"

script: cmake -H. -Bbuild && cmake --build build -- -j2
